FROM 741021400780.dkr.ecr.us-west-2.amazonaws.com/alpine-nodejs-tools:3.7-9.5.0-5.6.0

# Install node dependencies; ensure this is before
# we copy in application-code to take advantage of layer caching.
ADD package.json /tmp/package.json
RUN cd /tmp && \
    npm install && \
    mkdir -p /opt/app && \
    cp -a /tmp/node_modules /opt/app/

# Copy in everything; including .git files as codecov will need them.
WORKDIR /opt/app
COPY . /opt/app
